-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

-- //sellnpc powder
profiles['powder'] = S{
    'prize powder',
    }



-- //sellnpc junk
profiles['junk'] = S{
	'Hare Meat',
	'Rotten Meat',
	'Cuir Bandana',
	'Mythril Ore',
	'Linen Cloth',
	'Distilled Water',
	'Prism Powder',
	'Mtl. Beastcoin',
	'Mercury',
	'Cactuar Needle',
	'Boyahda Moss',
	'Golem Shard',
	'Manticore Hide',
	'Antican Pauldron',
	'Antican Robe',
	'Manticore Fang',
	'Manticore Hair',
	'Doll Shard',
	'Cactus Stems',
	'H.Q. Scp. shell',
	'Arnica Root',
	'Cactus Arm',
	'Antican Acid',
	'Fire III',
	'Stone IV',
	'Stonega II',
	'Stonega III',
	'Absorb-AGI',
	'Absorb-INT',
	'Ice Spirit',
	'Dark Spirit',
	'Buffalo Meat',
	'Uleguerand Milk',
	'Iron Arrow',
	'Snoll Arm',
	'Gaia Mantle',
	'Behemoth Mantle',
	'Demons Ring',
	'Jadeite Ring',
	'Zircon Ring',
	'Fluorite Ring',
	'Chrysoberyl Ring',
	'Ahriman Lens',
	'Demon Skull',
	'Demon Horn',
	'Ahriman Tears',
	'Ahriman Wing',
	'Hecteyes Eye',
	'Taurus Horn',
	'Taurus Wing',
	'Linen Robe',
	'Brigandine',
	'Lizard Helm',
	'Banded Mail',
	'Chocomilk',
	'Rarab Tail',
	'Focus Collar',
	'Opal Earring',
	'Amber Ring',
	'Quadav Helm',
	'Cotton Cloth',
	'Rock Salt',
	'Bird Egg',
	'Shell Bug',
	'Zinc Ore',
	'Rabbit Hide',
	'Blk. Tiger Fang',
	'Beehive Chip',
	'Malboro Vine',
	'Revival Root',
	'Treant Bulb',
	'Marble',
	'Helmet Mole',
	'Imp Wing',
	'Rusty Medal',
	"Magicked Blood",
	'Pamama au Lait',
	'Apkallu egg',
	'red rock',
	'Dryad Root',
	'G. bird plume',
	'Tonberry coat',
	'tonberry lantern',
	'tree saplings',
	'dried mugwort',
	'porxie wing',
	'velkk necklace',
	'Karugo clay',
	'eudaemon ring',
	'grove cuttings',
	'cockatrice skin',
	'Megalodon',
	'Mola Mola',
	'Steel Ingot',
	'Cockatrice Meat',
	'Dhalmel Pie',
	'Dhalmel meat',
	'Coeurl Meat',
	'Flint Caviar',
	'Antacid',
	'Vegetable seeds',
	'remora',
	'X-Potion +3',
	'Yorchete',
	'Dragon Scales',
	'Counterfeit Gil',
	'Wildgrass seeds',
	'Gargouille Eye',
	'Veydal Wrasse',
	'Scream Fungus',
	'Isleracea',
	'Flax Flower',
	'Mistletoe',
	'Dwarf Remora',
	'Bat wing',
	'Crawler calculus',
	'Misx. Parsley',
	'Beastcoin',
	'Wijnruit',
	'Super Ether',
	'Crawler egg',
	'Crawler cocoon',
	'2Leaf mandra bud',
	'Danceshroom',
	'Carnation',
	'Marble Nugget',
	'Puffball',
	'Zucchini',
	'Herb Seeds',
	'Grain Seeds',
	'Fruit Seeds',
	'Dragon Talon',
	'win. tea leaves',
	'Hi-Elixir',
	'Eggplant',
	--'Selbina Milk',
	'Lanolin',
	'Ether',
	'Stone',
	'Stone II',
	'Earth Spirit',
	'Mushrm. Locust',
	'Fresh Marjoram',
	'Tiny Goldfish',
	'Dragonfish',
	'Yagudo Cherry',
	'Sunflower Seeds',
	'Burdock',
	'Nopales',
	'Napa',
	'Red Rose',
	'King Locust',
	'Rolanberry',
	--'Watermelon', (Goblin Drink Mat)
	--'Felicifruit', (Tropical Crepe Mat)
	--'moko Grass',
	'Saruta cotton',
	'Bone chip',
	'Pebble',
	'Woozyshroom',
	'Sleepshroom',
	'Ruszor Meat',
	--'Silver ore',
	'Bird Feather',
	'Lizard Skin',
	'Fiend Blood',
	'Spider Web',
	'Lizard Tail',
	'Iron Sand',
	'Ruszor Fang',
	'Lik',
	'Dragon Fruit',
	'Elm Log',
	'Scorpion Claw',
	'Chicken Bone',
	'Verboshroom',
	'Bloodwood log',
	'insect wing',
	'fresh Mugwort',
	'lesser chigoe',
	'locust elutriator',
	--'akaso',
    'Aurora bass',
	'copper ore',
    'tin ore',
	'Igneous rock',
	'flint stone',
	'Meteorite',
	'pugil scales',
	'Sheep tooth',
	'Fish Bones',	
	'Bat fang',
	'Beetle Jaw',
	'Beetle shell',
	'Water Lily',
	'Crab shell',
	'H.Q. Crab shell',
	'Land Crab Meat',
	'Scorpion Shell',
	'Skull locust',
	'turtle shell',
	'ram horn',
	'antlion jaw',
	'dragon bone',
    'Bluetail',
    --'Bloodblotch', Zaldon!
	'Black Ghost',
	'titanictus',
	'brass loach',
	'Ulbukan lobster',
	'sea zombie',
	'red terrapin',
	'mackerel',
	'Barnacle',
	'Gold Carp',
	'Giant Catfish',
	'Crayfish',
	--'red moko grass',
	'Shall Shell',
	'Copper Frog',
	'Moorish Idol',
	'Yayinbaligi',
	'Crescent fish',
	'Contortopus',
	'Gigant Squid',
	'Zebra Eel',
	'Black Eel',
	--'Quus',
	'Gugru Tuna',
	--'Elshimo Newt', (Goblin Drink Mat)
	'Ca Cuong',
	'Senroh Sardine',
	'Ruddy Seema',
	'Cone Calamary',
	'Bhefhel Marlin',
	'Gavial fish',
	'Bastore Bream',
	'Ryugu Titan',
	'Black Sole',
	'Grimmonite',
	'Seashell',
	'Cobalt Jellyfish',
	'Three-eyed fish',
	'black prawn',
	'Rusty Bucket',
	'Dark Bass',
	'Pipira',
    'chestnut',
    --'san d\'Or. carrot', (Goblin Drink Mat)
	--'Persikos', (Tropical Crepe Mat)
	'potion',
	'potion +1',
	'potion +2',
	'Giant Bird Feather',
	'adoulinian kelp',
	'lacquer tree log',
	'Faerie Apple',
	'Date',
	'Butterpear',
	'Melon Pie',
	'Pamamas',
	'Walnut',
	--'Kitron', (Tropical Crepe Mat)
	'Ulbuconut',
	'Arrowwood log',
	'divine log',
	'Auric sand',
	'Maple log',
	'Mahogany log',
	'Elshimo Pachira Fruit',
	'Ebony log',
	'Chestnut log',
	'Oak Log',
	'Urunday log',
	'Acorn',
	'Walnut log',
	'Ash Log',
	'Dogwood log',
	'Tree Cuttings',
	'Snapping mole',
	'Pine Nuts',
	'Lizard Egg',
	'Eft Skin',
    }

return profiles
