return {
    { zone = "La Theine Plateau", camp_level = "8-13", camp_position = "Entire zone", notes = "Start from the beginning of the zone and continue toward Valkurm Dunes", monsters = { "Orcs", "Sheep", "Birds", "Goblins", "Crabs", "Bats", "Bees", "Worms" } },
    { zone = "Konschtat Highlands", camp_level = "8-13", camp_position = "Entire Zone", notes = "Start from the beginning of the zone and continue toward Valkurm Dunes.", monsters = { "Quadav", "Sheep", "Birds", "Goblins", "Lizards", "Bats", "Bees", "Worms" } },
    { zone = "Tahrongi Canyon", camp_level = "8-13", camp_position = "Entire Zone", notes = "Start at beginning of the zone and work your way toward Buburimu Peninsula. Camp around there and the Crag of Mea.", monsters = { "Yagudo", "Mandragora", "Birds", "Goblins", "Crawler", "Dhalmel", "Bees" } },
    { zone = "Valkurm Dunes", camp_level = "12-20", camp_position = "L-9/10<br />M-9/10", notes = "", monsters = { "Hill Lizard", "Goblins" } },
    { zone = "Valkurm Dunes", camp_level = "13-25", camp_position = "Oasis<br />Three Beaches<br />etc", notes = "", monsters = { "Snipper", "Damselfly", "Brutal Sheep", "Goblins", "Beach Pugil" } },
    { zone = "Korroloka Tunnel", camp_level = "15-25", camp_position = "C-9", notes = "Next to Survival Guide", monsters = { "Land Worm", "Seeker Bats" } },
    { zone = "Qufim Island", camp_level = "20-25", camp_position = "I-8", notes = "", monsters = { "Land Worm" } },
    { zone = "Qufim Island", camp_level = "20-25", camp_position = "H-7", notes = "Around the pond", monsters = { "Land Worm" } },
    { zone = "Qufim island", camp_level = "25-29", camp_position = "H-7", notes = "Around the Pond", monsters = { "Clipper" } },
    { zone = "Qufim island", camp_level = "25-29", camp_position = "H-6", notes = "In the Chasm", monsters = { "Clipper", "Greater Pugil", "Acrophies (27+)" } },
    { zone = "Lower Delkfutt's Tower", camp_level = "25-35", camp_position = "Map 1", notes = "Use Lower Delkfuutt's Tower HP Warp #1", monsters = { "Gigas" } },
    { zone = "Upper Delkfutt's Tower", camp_level = "35-42", camp_position = "Map 1", notes = "Use Upper Delkfuutt's Tower HP Warp #1", monsters = { "Gigas" } },
    { zone = "Oldton Movalpolos", camp_level = "31-50", camp_position = "''Everywhere''", notes = "Yes, Really", monsters = { "Oldton Movalpolos" } },
    { zone = "Crawler's Nest", camp_level = "32-42", camp_position = "K-8", notes = "Near the entrance.", monsters = { "Worker Crawler", "Death Jacket", "Maze Lizard" } },
    { zone = "Garlaige Citadel", camp_level = "32-42", camp_position = "G-7/I-9", notes = "At entrance and Banishing Gate #1<br />(Map 1)", monsters = { "Siege Bat", "Borer Beetle" } },
    { zone = "Rolanberry Fields (S)", camp_level = "44-52", camp_position = "G-11, H-9 to J-10 and E-8 to F-9", notes = "Small Blobs of enemies.", monsters = { "Coppercap", "Berry Grub" } },
    { zone = "Bostaunieux Oubliette", camp_level = "45-55", camp_position = "I-6 to G-8", notes = "Camp is in Map 2. Drop down at (E-8) in Map 1.<br />", monsters = { "Funnel Bats", "Werebat" } },
    { zone = "Escha - Zi'Tah", camp_level = "45-55", camp_position = "Around (E-8/9)", notes = "", monsters = { "Eschan Worm", "Eschan Crawler" } },
    { zone = "Escha - Zi'Tah", camp_level = "50-68", camp_position = "Around (E-7/8)", notes = "", monsters = { "Eschan Dhalmel", "Eschan Coeurl", "Eschan Weapon" } },
    { zone = "Kuftal Tunnel", camp_level = "55-60", camp_position = "I-8", notes = "At entrance from Western Altepa Desert.<br />", monsters = { "Robber Crab", "Sand Lizard" } },
    { zone = "Kuftal Tunnel", camp_level = "55-60", camp_position = "G-3/H-3", notes = "Near the exit to Cape Teriggan. <br />", monsters = { "Robber Crab", "Sand Lizard" } },
    { zone = "Wajaom Woodlands", camp_level = "55-65", camp_position = "K-7", notes = "<br />", monsters = { "Lesser Colibri" } },
    { zone = "Wajaom Woodlands", camp_level = "55-65", camp_position = "G-8", notes = "<br />", monsters = { "Lesser Colibri" } },
    { zone = "Bhaflau Thickets", camp_level = "55-65", camp_position = "H-9/H-10/I-8", notes = "<br />", monsters = { "Lesser Colibri" } },
    { zone = "Cape Teriggan", camp_level = "58-64", camp_position = "G/H-8", notes = "", monsters = { "Beach Bunny", "Sand Lizard" } },
    { zone = "Bostaunieux Oubliette", camp_level = "60-70", camp_position = "F-9/10", notes = "Map 3", monsters = { "Bloodsucker" } },
    { zone = "Labyrinth of Onzozo", camp_level = "60-70", camp_position = "F-6 to H-6", notes = "", monsters = { "Torama", "Labyrinth Manticore" } },
    { zone = "Cape Teriggan", camp_level = "64-71", camp_position = "I-7", notes = "", monsters = { "Sand Cockatrice", "Velociraptor" } },
    { zone = "Bhaflau Thickets", camp_level = "65-70", camp_position = "F-8/G-8", notes = "Right outside Halvung(2) entrance.<br />", monsters = { "Colibri", "Date Eruca", "Troll Surveillant", "Troll Shieldbearer", "Troll Sabreur" } },
    { zone = "Escha - Zi'Tah", camp_level = "70-80", camp_position = "Around (G-9/H-9)", notes = "", monsters = { "Eschan Sorceror", "Eschan Corse", "Eschan Vulture" } },
    { zone = "Bibiki Bay", camp_level = "70-73", camp_position = "G-6", notes = "", monsters = { "Tropical Rarab", "Tragopan" } },
    { zone = "Bhaflau Thickets", camp_level = "70-75", camp_position = "I-9", notes = "Outside Mamook(2) entrance.<br />", monsters = { "Sea Puk", "Mamool Ja" } },
    { zone = "Zeruhn Mines", camp_level = "70-78", camp_position = "I-9", notes = "<br />", monsters = { "Burrower Worm", "Colliery Bat", "Soot Crab", "Veindigger Leech" } },
    { zone = "Escha - Ru'Aun", camp_level = "70-83", camp_position = "G-10 to I-10", notes = "", monsters = { "Eschan Zdei" } },
    { zone = "Kuftal Tunnel", camp_level = "72-80", camp_position = "G-9 on Map 2", notes = "Past [[Kuftal Tunnel#Notes|the rock that will ocasionally block your path]].<br />", monsters = { "Ovinnik", "Greater Cockatrice", "Ladon" } },
    { zone = "Misareaux Coast", camp_level = "75 - 79/80", camp_position = "G-7 and J-8", notes = "", monsters = { "Seaboard Vulture" } },
    { zone = "Escha - Zi'Tah", camp_level = "80-89", camp_position = "Around (G-10/11)", notes = "", monsters = { "Eschan Snapweed", "Eschan Wasp", "Eschan Goobbue" } },
    { zone = "Mount Zhayolm", camp_level = "80-89", camp_position = "C-9", notes = "", monsters = { "Orichalcumshell" } },
    { zone = "Dangruf Wadi", camp_level = "80-90", camp_position = "I-8", notes = "Use the geyser to go up the ledge", monsters = { "Witchetty Grub", "Prim Pika", "Goblin Headsman", "Goblin Healer", "Goblin Brigand", "Goblin Bladesmith", "Goblin Bushwhacker", "Trimmer", "Natty Gibbon" } },
    { zone = "Caedarva Mire", camp_level = "80-85", camp_position = "F-9 Map 1", notes = "Short walk from HP #1", monsters = { "Slough Skua" } },
    { zone = "Gusgen Mines", camp_level = "80-84", camp_position = "F-8 (Map 2)", notes = "Straight back and through the left tunnel.", monsters = { "Rockmill" } },
    { zone = "Meriphataud Mountains (S)", camp_level = "84-94", camp_position = "F/G-8/9", notes = "South of the Recall Point", monsters = { "Condor (Monster)" } },
    { zone = "Dangruf Wadi", camp_level = "85-92", camp_position = "J-4 and H-3", notes = "", monsters = { "Trimmer", "Natty Gibbon" } },
    { zone = "Rolanberry Fields (S)", camp_level = "85-92", camp_position = "F-8/G-8", notes = "", monsters = { "Champion Crawler" } },
    { zone = "North Gustaberg (S)", camp_level = "85-92", camp_position = "D-8/E-8", notes = "", monsters = { "Drachenlizard" } },
    { zone = "Vunkerl Inlet (S)", camp_level = "85-92", camp_position = "H-7", notes = "", monsters = { "Duriumshell" } },
    { zone = "Jugner Forest (S)", camp_level = "85-92", camp_position = "J-10/K-10", notes = "", monsters = { "Gnoletrap" } },
    { zone = "Ceizak Battlegrounds", camp_level = "90-99", camp_position = "J-8/9/10", notes = "Near the beaches", monsters = { "Blanched Mandragora" } },
    { zone = "Yahse Hunting Grounds", camp_level = "90-99", camp_position = "Around K-7~10", notes = "Near the beaches", monsters = { "Pinetorum", "Bight Uragnite" } },
    { zone = "Gustav Tunnel", camp_level = "90-99", camp_position = "I-7", notes = "", monsters = { "Boulder Eater", "Pygmytoise" } },
    { zone = "Kuftal Tunnel", camp_level = "90-99", camp_position = "G-9 on Map 3", notes = "Past Map 2 (E) at the [[Kuftal Tunnel#Notes|the rock that will ocasionally block your path]].<br />", monsters = { "Machairodus", "Kuftal Delver" } },
    { zone = "Yahse Hunting Grounds", camp_level = "90-99", camp_position = "(J-7)<br>(J-8)<br>(J-9)", notes = "", monsters = { "Calfcleaving Chapuli" } },
    { zone = "Rala Waterways", camp_level = "90-99", camp_position = "G-6/H-6", notes = "Camp at the mouth of the rectangular area.", monsters = { "Depthswalker Crab", "Barnacle Crab" } },
    { zone = "Escha - Zi'Tah", camp_level = "107-110", camp_position = "Around (F-5/6)", notes = "", monsters = { "Eschan Shadow Dragon" } },
}
