-- exptips/init.lua

_addon.name    = 'exptips'
_addon.version = '1.1'
_addon.author  = 'Uncle Awesome'
_addon.commands = {'xpt'}

require('logger')

-- ============================================================================
--  Load EXP camp data (generated by your Python scraper)
-- ============================================================================
local exp_data = require('exp_data')   -- exp_data.lua must return a table
local skill_grades = require('skill_grades')

-- ============================================================================
--  Utility helpers
-- ============================================================================
local function strip_html(text)
    if not text or text == '' then
        return ''
    end
    text = text:gsub('<br%s*/?>', ' '):gsub('<.->', '')
    text = text:gsub('%s+', ' '):gsub('^%s*(.-)%s*$', '%1')
    return text
end

local function format_skill_name(key)
    return key:gsub("_", " "):gsub("(%l)(%w*)", function(a,b) return a:upper()..b end)
end

local function get_player_level()
    local p = windower.ffxi.get_player()
    return p and p.main_job_level or nil
end

local function level_in_range(range, lvl)
    local min, max = range:match('(%d+)%s*%-%s*(%d+)')
    min, max = tonumber(min), tonumber(max)
    return min and max and lvl >= min and lvl <= max
end

local function find_exp_camps(lvl)
    local list = {}
    for _, e in ipairs(exp_data) do
        if e.camp_level and level_in_range(e.camp_level, lvl) then
            table.insert(list, e)
        end
    end
    return list
end

local function show_matches(lvl)
    local camps = find_exp_camps(lvl)
    if #camps == 0 then
        windower.add_to_chat(207, string.format('No EXP camps found for level %d.', lvl))
        return
    end

    windower.add_to_chat(207, string.format('EXP Camps for level %d:', lvl))
    for _, c in ipairs(camps) do
        local camp_pos = strip_html(c.camp_position or 'Unknown position')
        local notes    = strip_html(c.notes or '')
        local monsters = (#c.monsters > 0) and table.concat(c.monsters, ', ') or '—'

        local line = string.format('[%s] (%s) %s', c.zone or 'Unknown', c.camp_level, camp_pos)
        if notes ~= '' then
            line = line .. ' - ' .. notes
        end
        windower.add_to_chat(207, line)
        windower.add_to_chat(207, '  Monsters: ' .. monsters)
    end
end

-- Skill cap formulas per grade
local cap_formulas = {
    ['A+'] = function(L) return 0.02317 * L^2 + 1.83135 * L + 10.9117 end,
    ['A']  = function(L) return 0.02435 * L^2 + 1.63707 * L + 11.6975 end,
    ['A-'] = function(L) return 0.02220 * L^2 + 1.56000 * L + 11.2500 end,  -- Estimated between A and B+

    ['B+'] = function(L) return 0.02147 * L^2 + 1.78143 * L + 10.0214 end,
    ['B']  = function(L) return 0.02030 * L^2 + 1.82675 * L + 9.8881 end,
    ['B-'] = function(L) return 0.01900 * L^2 + 1.86400 * L + 9.7770 end,   -- Estimated below B

    ['C+'] = function(L) return 0.01730 * L^2 + 1.95000 * L + 9.3000 end,   -- Estimated between B- and C
    ['C']  = function(L) return 0.01600 * L^2 + 2.00000 * L + 9.0000 end,   -- Approximation
    ['C-'] = function(L) return 0.01480 * L^2 + 2.05000 * L + 8.7000 end,   -- Estimated lower than C

    ['D+'] = function(L) return 0.01350 * L^2 + 2.10000 * L + 8.2000 end,   -- Between C- and D
    ['D']  = function(L) return 0.01143 * L^2 + 2.07933 * L + 6.0282 end,
    ['D-'] = function(L) return 0.01000 * L^2 + 2.05000 * L + 5.5000 end,   -- Below D

    ['E+'] = function(L) return 0.00850 * L^2 + 2.00000 * L + 5.0000 end,   -- Approximated
    ['E']  = function(L) return 0.00700 * L^2 + 1.95000 * L + 4.5000 end,   -- Approximated
    ['E-'] = function(L) return 0.00550 * L^2 + 1.90000 * L + 4.0000 end,   -- Approximated
}

-- ==========================================================================
--  Command handler
-- ==========================================================================
windower.register_event('addon command', function(arg1, ...)
    local args = {...}
    local level

    if arg1 == nil or arg1 == '' then
        level = get_player_level()
        if not level then
            windower.add_to_chat(123, 'Could not detect your level. Use: //xpt <level>')
            return
        end
        show_matches(level)

    elseif arg1:lower() == 'help' then
        windower.add_to_chat(207, 'Exptips help:')
        windower.add_to_chat(207, '  //xpt               Shows EXP camps for your current level')
        windower.add_to_chat(207, '  //xpt <level>       Shows EXP camps for that level (e.g., //xpt 56)')
        windower.add_to_chat(207, '  //xpt monster <mob> EXP camps with that monster (e.g., //xpt monster colibri)')
        windower.add_to_chat(207, '  //xpt skillcap      Show estimated skill caps for your job and level')

    elseif arg1:lower() == 'monster' and args[1] then
        local query = table.concat(args, ' '):lower()
        local matches = {}

        for _, entry in ipairs(exp_data) do
            if entry.monsters then
                for _, monster in ipairs(entry.monsters) do
                    if monster:lower():find(query) then
                        table.insert(matches, entry)
                        break
                    end
                end
            end
        end

        if #matches == 0 then
            windower.add_to_chat(207, ("No EXP camps found for monster: %s"):format(query))
        else
            windower.add_to_chat(207, ("EXP Camps with monster: %s"):format(query))
            for _, match in ipairs(matches) do
                local line = string.format("[%s] (%s): %s", match.zone or "Unknown", match.camp_level or "?", match.notes or "")
                windower.add_to_chat(200, line)
                if match.monsters and #match.monsters > 0 then
                    windower.add_to_chat(001, "  Monsters: " .. table.concat(match.monsters, ", "))
                end
            end
        end

    elseif arg1:lower() == 'skillcap' or arg1:lower() == 'sc' then
        local p = windower.ffxi.get_player()
        if not p or not p.main_job or not p.main_job_level then
            windower.add_to_chat(207, 'Could not detect your job and level.')
            return
        end

        local job = p.main_job:upper()
        local level = p.main_job_level
        local grades = skill_grades[job]

        if not grades then
            windower.add_to_chat(207, string.format("No skill grade data for job: %s", p.main_job))
            return
        end

        windower.add_to_chat(207, string.format("%s Skill Caps at Level %d:", job, level))

        for skill, grade in pairs(grades) do
            local formula = cap_formulas[grade]
            if formula then
                local cap = math.floor(formula(level) + 0.5)
                local skill_name = format_skill_name(skill)
                windower.add_to_chat(207, string.format("  %s: %d (%s)", skill_name, cap, grade))
            else
                local skill_name = format_skill_name(skill)
                windower.add_to_chat(207, string.format("  %s: Unknown cap (grade %s not supported)", skill_name, grade))
            end
        end

    else
        level = tonumber(arg1)
        if not level then
            windower.add_to_chat(207, 'Invalid level. Usage: //xpt <level>  (example: //xpt 56)')
            return
        end
        show_matches(level)
    end
end)
