-- exptips/init.lua

_addon.name    = 'exptips'
_addon.version = '1.1'
_addon.author  = 'Uncle Awesome'
_addon.commands = {'exptips'}

require('logger')

-- ============================================================================
--  Load EXP camp data (generated by your Python scraper)
-- ============================================================================
local exp_data = require('exp_data')   -- exp_data.lua must return a table

-- ============================================================================
--  Utility helpers
-- ============================================================================
--- Strips simple HTML tags (e.g. <br>, <br/>, <br />) and trims whitespace
---@param text string
---@return string
local function strip_html(text)
    if not text or text == '' then
        return ''
    end
    text = text:gsub('<br%s*/?>', ' '):gsub('<.->', '')  -- remove other tags if any
    -- collapse multiple spaces and trim
    text = text:gsub('%s+', ' '):gsub('^%s*(.-)%s*$', '%1')
    return text
end

--- Returns the player's main‑job level or nil if unavailable
local function get_player_level()
    local p = windower.ffxi.get_player()
    return p and p.main_job_level or nil
end

--- Checks whether a numeric level falls inside a range string like "8-13"
---@param range string  "min-max"
---@param lvl   number
---@return boolean
local function level_in_range(range, lvl)
    local min, max = range:match('(%d+)%s*%-%s*(%d+)')
    min, max = tonumber(min), tonumber(max)
    return min and max and lvl >= min and lvl <= max
end

--- Filters exp_data for camps that include the given level
---@param lvl number
---@return table
local function find_exp_camps(lvl)
    local list = {}
    for _, e in ipairs(exp_data) do
        if e.camp_level and level_in_range(e.camp_level, lvl) then
            table.insert(list, e)
        end
    end
    return list
end

--- Displays matching camps in chat
---@param lvl number
local function show_matches(lvl)
    local camps = find_exp_camps(lvl)
    if #camps == 0 then
        windower.add_to_chat(207, string.format('No EXP camps found for level %d.', lvl))
        return
    end

    windower.add_to_chat(207, string.format('EXP Camps for level %d:', lvl))
    for _, c in ipairs(camps) do
        local camp_pos = strip_html(c.camp_position or 'Unknown position')
        local notes    = strip_html(c.notes or '')
        local monsters = (#c.monsters > 0) and table.concat(c.monsters, ', ') or '—'

        local line = string.format('[%s] (%s) %s', c.zone or 'Unknown', c.camp_level, camp_pos)
        if notes ~= '' then
            line = line .. ' - ' .. notes
        end
        windower.add_to_chat(207, line)
        windower.add_to_chat(207, '  Monsters: ' .. monsters)
    end
end

-- ============================================================================
--  Command handler
-- ============================================================================
windower.register_event('addon command', function(arg1)
    local level
    if arg1 and arg1 ~= '' then
        level = tonumber(arg1)
        if not level then
            windower.add_to_chat(123, 'Usage: //exptips <level>  (example: //exptips 56)')
            return
        end
    else
        level = get_player_level()
        if not level then
            windower.add_to_chat(123, 'Could not detect your level. Use: //exptips <level>')
            return
        end
    end
    show_matches(level)
end)
