-- exptips/init.lua

_addon.name    = 'exptips'
_addon.version = '1.1'
_addon.author  = 'Uncle Awesome'
_addon.commands = {'xpt'}

require('logger')

-- ============================================================================
--  Load EXP camp data (generated by your Python scraper)
-- ============================================================================
local exp_data = require('exp_data')   -- exp_data.lua must return a table

-- ============================================================================
--  Utility helpers
-- ============================================================================
--- Strips simple HTML tags (e.g. <br>, <br/>, <br />) and trims whitespace
---@param text string
---@return string
local function strip_html(text)
    if not text or text == '' then
        return ''
    end
    text = text:gsub('<br%s*/?>', ' '):gsub('<.->', '')  -- remove other tags if any
    -- collapse multiple spaces and trim
    text = text:gsub('%s+', ' '):gsub('^%s*(.-)%s*$', '%1')
    return text
end

--- Returns the player's main‑job level or nil if unavailable
local function get_player_level()
    local p = windower.ffxi.get_player()
    return p and p.main_job_level or nil
end

--- Checks whether a numeric level falls inside a range string like "8-13"
---@param range string  "min-max"
---@param lvl   number
---@return boolean
local function level_in_range(range, lvl)
    local min, max = range:match('(%d+)%s*%-%s*(%d+)')
    min, max = tonumber(min), tonumber(max)
    return min and max and lvl >= min and lvl <= max
end

--- Filters exp_data for camps that include the given level
---@param lvl number
---@return table
local function find_exp_camps(lvl)
    local list = {}
    for _, e in ipairs(exp_data) do
        if e.camp_level and level_in_range(e.camp_level, lvl) then
            table.insert(list, e)
        end
    end
    return list
end

--- Displays matching camps in chat
---@param lvl number
local function show_matches(lvl)
    local camps = find_exp_camps(lvl)
    if #camps == 0 then
        windower.add_to_chat(207, string.format('No EXP camps found for level %d.', lvl))
        return
    end

    windower.add_to_chat(207, string.format('EXP Camps for level %d:', lvl))
    for _, c in ipairs(camps) do
        local camp_pos = strip_html(c.camp_position or 'Unknown position')
        local notes    = strip_html(c.notes or '')
        local monsters = (#c.monsters > 0) and table.concat(c.monsters, ', ') or '—'

        local line = string.format('[%s] (%s) %s', c.zone or 'Unknown', c.camp_level, camp_pos)
        if notes ~= '' then
            line = line .. ' - ' .. notes
        end
        windower.add_to_chat(207, line)
        windower.add_to_chat(207, '  Monsters: ' .. monsters)
    end
end

-- ============================================================================
--  Command handler
-- ============================================================================
windower.register_event('addon command', function(arg1, ...)
    local args = {...}
    local level

    if arg1 == nil or arg1 == '' then
        -- No argument: use player's level
        level = get_player_level()
        if not level then
            windower.add_to_chat(123, 'Could not detect your level. Use: //xpt <level>')
            return
        end
        show_matches(level)

    elseif arg1:lower() == 'help' then
        windower.add_to_chat(207, 'Exptips help:')
        windower.add_to_chat(207, '  //xpt               Shows EXP camps for your current level')
        windower.add_to_chat(207, '  //xpt <level>       Shows EXP camps for that level (e.g., //xpt 56)')
        windower.add_to_chat(207, '  //xpt monster <mob> EXP camps with that monster (e.g., //xpt monster colibri)')
        windower.add_to_chat(207, '  //xpt help          Displays this help message')

        -- # TODO: windower.add_to_chat(207, '  //xpt zone <zone>   → EXP camps in that zone')

        -- # TODO: Specify the monster type, i.e. RoE quest types. arcana, birds, etc...
    elseif arg1:lower() == 'monster' and args[1] then
        local query = table.concat(args, ' '):lower()
        local matches = {}

        for _, entry in ipairs(exp_data) do
            if entry.monsters then
                for _, monster in ipairs(entry.monsters) do
                    if monster:lower():find(query) then
                        table.insert(matches, entry)
                        break
                    end
                end
            end
        end

        if #matches == 0 then
            windower.add_to_chat(207, ("No EXP camps found for monster: %s"):format(query))
        else
            windower.add_to_chat(207, ("EXP Camps with monster: %s"):format(query))
            for _, match in ipairs(matches) do
                local line = string.format("[%s] (%s): %s", match.zone or "Unknown", match.camp_level or "?", match.notes or "")
                windower.add_to_chat(200, line)
                if match.monsters and #match.monsters > 0 then
                    windower.add_to_chat(001, "  Monsters: " .. table.concat(match.monsters, ", "))
                end
            end
        end

    else
        level = tonumber(arg1)
        if not level then
            windower.add_to_chat(123, 'Invalid level. Usage: //xpt <level>  (example: //xpt 56)')
            return
        end
        show_matches(level)
    end
end)

-- windower.register_event('addon command', function(arg1)
--     local level
--     if arg1 and arg1 ~= '' then
--         level = tonumber(arg1)
--         if not level then
--             windower.add_to_chat(123, 'Usage: //xpt <level>  (example: //xpt 56)')
--             return
--         end
--     else
--         level = get_player_level()
--         if not level then
--             windower.add_to_chat(123, 'Could not detect your level. Use: //xpt <level>')
--             return
--         end
--     end
--     show_matches(level)
-- end)
