return {
    WAR = {
        GreatAxe = 'A+',
        Axe = 'A',
        GreatSword = 'B+',
        Scythe = 'B+',
        Sword = 'B',
        Staff = 'B',
        Dagger = 'B-',
        Polearm = 'B-',
        Club = 'B-',
        Shield = 'C+',
        Evasion = 'C',
        Parrying = 'C-',
        HandToHand = 'D',
        Archery = 'D',
        Marksmanship = 'D',
    },

    MNK = {
        HandToHand = 'A+',
        Guard = 'A',
        Evasion = 'B+',
        Staff = 'B',
        Club = 'C+',
        Throwing = 'E',
        Parrying = 'E',
    },

    WHM = {
        Healing = 'A+',
        Divine = 'A',
        Club = 'B+',
        Staff = 'C+',
        Enhancing = 'C+',
        Enfeebling = 'C',
        Shield = 'D',
        Throwing = 'E',
        Evasion = 'E',
    },

    BLM = {
        Elemental = 'A+',
        Staff = 'B+',
        Enfeebling = 'B+',
        Dark = 'B',
        Club = 'D',
        Throwing = 'E',
        Evasion = 'E',
        Shield = 'E',
    },

    RDM = {
        Enfeebling = 'A+',
        Dagger = 'B',
        Enhancing = 'B',
        Healing = 'C+',
        Sword = 'C+',
        Elemental = 'C+',
        Club = 'C',
        Parrying = 'C',
        Staff = 'C',
        Dark = 'C',
        Evasion = 'D',
        Shield = 'D',
        Throwing = 'E',
    },

    THF = {
        Dagger = 'A+',
        Evasion = 'A',
        Sword = 'C+',
        Throwing = 'C',
        Marksmanship = 'C',
        Parrying = 'C',
        HandToHand = 'E',
    },

    PLD = {
        Sword = 'A+',
        Shield = 'A+',
        Healing = 'B+',
        Divine = 'B',
        Club = 'B',
        GreatSword = 'C+',
        Polearm = 'C+',
        Dagger = 'C',
        Staff = 'C',
        Parrying = 'C',
        Enfeebling = 'C',
        Evasion = 'D',
        HandToHand = 'E',
    },

    DRK = {
        GreatSword = 'A+',
        Scythe = 'A+',
        Dark = 'A+',
        Enfeebling = 'C+',
        Sword = 'C',
        Staff = 'C',
        Parrying = 'C',
        Elemental = 'C',
        Evasion = 'D',
        HandToHand = 'E',
    },

    BST = {
        Axe = 'A+',
        Sword = 'C+',
        Club = 'C+',
        Dagger = 'C+',
        Scythe = 'C',
        Staff = 'C',
        Evasion = 'C',
        Parrying = 'C',
        HandToHand = 'D',
    },

    BRD = {
        Singing = 'A+',
        String = 'B+',
        Wind = 'B+',
        Dagger = 'B',
        Sword = 'C+',
        Club = 'C+',
        Staff = 'C',
        Evasion = 'D',
        Shield = 'D',
    },

    RNG = {
        Archery = 'A+',
        Marksmanship = 'A+',
        Axe = 'B',
        Dagger = 'C',
        Sword = 'C',
        Evasion = 'C',
        Parrying = 'C',
    },

    SAM = {
        GreatKatana = 'A+',
        Archery = 'B+',
        Polearm = 'B',
        Staff = 'C+',
        Parrying = 'C',
        Katana = 'D',
        Evasion = 'D',
    },

    NIN = {
        Katana = 'A+',
        Ninjutsu = 'A+',
        Evasion = 'A+',
        Dagger = 'B+',
        Throwing = 'B+',
        Parrying = 'B',
        Sword = 'C',
    },

    DRG = {
        Polearm = 'A+',
        Sword = 'C+',
        Staff = 'C',
        Dagger = 'C',
        Evasion = 'C',
        Parrying = 'C',
        HandToHand = 'D',
    },

    SMN = {
        Summoning = 'A+',
        Staff = 'B+',
        Club = 'C',
        Throwing = 'E',
        Evasion = 'E',
        Shield = 'E',
    },

    BLU = {
        Sword = 'A+',
        BlueMagic = 'A+',
        Evasion = 'B+',
        Dagger = 'B',
        HandToHand = 'C',
        Parrying = 'C',
        Club = 'C',
    },

    COR = {
        Marksmanship = 'A+',
        Dagger = 'B',
        Evasion = 'B',
        Sword = 'C',
        Parrying = 'C',
        HandToHand = 'E',
    },

    PUP = {
        HandToHand = 'A+',
        Automaton = 'A+',
        Evasion = 'B+',
        Club = 'C+',
        Parrying = 'C',
        Staff = 'D',
    },

    DNC = {
        Dagger = 'A+',
        Evasion = 'A+',
        Healing = 'B+',
        Sword = 'C+',
        Parrying = 'C+',
        Enhancing = 'C',
        HandToHand = 'E',
    },

    SCH = {
        Elemental = 'A+',
        Staff = 'B+',
        Healing = 'B',
        Enhancing = 'B',
        Enfeebling = 'B',
        Dark = 'B',
        Club = 'C+',
        Throwing = 'E',
        Evasion = 'E',
        Shield = 'E',
    },

    GEO = {
        Geomancy = 'A+',
        Handbell = 'A+',
        Enfeebling = 'B+',
        Club = 'B+',
        Elemental = 'B',
        Staff = 'C+',
        Throwing = 'E',
        Evasion = 'E',
        Shield = 'E',
    },

    RUN = {
        GreatSword = 'A+',
        Enhancing = 'A',
        Sword = 'B+',
        Evasion = 'B+',
        Shield = 'C+',
        Staff = 'C',
        Club = 'C',
        Parrying = 'C',
        Enfeebling = 'C',
    }
}
